scene_name: ???
output_dir: /scratch/izar/cizinsky/thesis/preprocessing/${scene_name}/lhm
exp_name: "dev"
epochs: 300
batch_size: 5
lr: 1e-3
weight_decay: 5e-4
grad_clip: 0.1
sample_every: 1
vis_every_epoch: 1
train_params:
  - offset_xyz
  - rotation
  - scaling
  - opacity
  - shs

wandb:
  enable: true
  project: "hybrid-lhm"
  entity: "ludekcizinsky"
  tags:
    - v2

loss_weights:
  rgb: 10.0
  sil: 2.0
  lpips: 0.2
  reg_asap: 200.0
  reg_acap: 200.0

tune_smplx: true


hydra:
  run:
    dir: /scratch/izar/cizinsky/thesis/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False
