scene_name: ???
num_persons: ???
output_dir: /scratch/izar/cizinsky/thesis/preprocessing/${scene_name}/lhm
exp_name: "dev"
epochs: 10
batch_size: 5
lr: 1e-4
weight_decay: 5e-4
grad_clip: 0.1
sample_every: 1
vis_every_epoch: 5
eval_every_epoch: 5
train_params: 
  - offset_xyz
  - rotation
  - scaling
  - opacity
  - shs

wandb:
  enable: true
  project: "hybrid-lhm"
  entity: "ludekcizinsky"
  tags:
    - v2

loss_weights:
  rgb: 20.0
  sil: 4.0
  ssim: 0.4
  depth: 0.1
  reg_asap: 200.0
  reg_acap: 200.0

tune_motion: true

nvs_eval:
  source_camera_id: 4
  target_camera_ids: [28, 52]
  root_gt_dir_path: /scratch/izar/cizinsky/ait_datasets/full/hi4d/pair00_1/fight00
  downscale_factor: 2


hydra:
  run:
    dir: /scratch/izar/cizinsky/thesis/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False
